name: Chireiden Nightly
on: push

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Checkout TShock
        uses: actions/checkout@v1
        with:
          submodules: recursive
          path: TSAPI
          repository: chi-rei-den/TSAPI/
          ref: dotnet5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build and Publish
        run: |
          cd ..
          dir
          ls
          cd TSAPI
          dotnet build TerrariaServerAPI/TerrariaServerAPI.csproj
          dotnet pack --version-suffix alpha --output nupkgs TerrariaServerAPI/TerrariaServerAPI.csproj
          dotnet nuget push nupkgs/*.nupkg -k ${{ secrets.ApiKey }} -s https://api.nuget.org/v3/index.json
