name: Nightly Build
on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        mode: ["Debug"]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Checkout TShock
      uses: actions/checkout@v1
      with:
        submodules: recursive
        path: TShock
        repository: Pryaxis/TShock/
        ref: general-devel

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.ApiKey }}
        nuget-version: '5.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: |
        cd ..\TShock
        nuget restore TerrariaServerAPI\TShock.4.OTAPI.sln
        nuget restore TShock.sln
        msbuild TerrariaServerAPI\TShock.4.OTAPI.sln /p:Configuration=${{ matrix.mode }}
        cd TerrariaServerAPI\TShock.Modifications.Bootstrapper\bin\${{ matrix.mode }}
        .\TShock.Modifications.Bootstrapper.exe
        cd ..\..\..\
        msbuild TerrariaServerAPI\TerrariaServerAPI.csproj /p:Configuration=${{ matrix.mode }}
        cd ..\
        msbuild TShockAPI\TShockAPI.csproj /p:Configuration=${{ matrix.mode }}
        dir
        cd ..\
        dir
        cd TShockNuGet
        dir
        python nightly_build.py
        nuget pack tshock.nuspec -OutputFileNamesWithoutVersion
        nuget push TerrariaServer.TShock.Nightly.nupkg -Source nuget.org -SkipDuplicate -NonInteractive -Verbosity detailed

    - uses: actions/upload-artifact@v1
      with:
        name: TerrariaServer.TShock.Nightly.nupkg
        path: TerrariaServer.TShock.Nightly.nupkg