name: Stable Build
on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.ApiKey }}
        nuget-version: '5.x'

    - name: Build
      shell: pwsh
      run: |
        python stable_build.py
        nuget pack tshock.nuspec -OutputFileNamesWithoutVersion
        nuget push TerrariaServer.TShock.nupkg -Source nuget.org -SkipDuplicate -NonInteractive -Verbosity detailed

    - uses: actions/upload-artifact@v1
      with:
        name: TerrariaServer.TShock.nupkg
        path: TerrariaServer.TShock.nupkg